# Configuration de la vectorisation - Assistant Pénal

vectorization:
  # Paramètres de découpage des documents
  chunk_size: 800  # Taille des chunks en caractères
  chunk_overlap: 100  # Chevauchement entre chunks
  
  # Modèle d'embedding OpenAI
  model: "text-embedding-ada-002"
  
  # Répertoire de persistance ChromaDB
  persist_directory: "data/vector_db"
  
  # Configuration des logs
  log_path: "logs/vector.log"
  log_level: "INFO"
  
  # Paramètres de traitement
  batch_size: 100  # Nombre de chunks par batch
  max_retries: 3  # Tentatives en cas d'échec
  retry_delay: 5  # Délai entre tentatives (secondes)
  
  # Métadonnées à extraire
  metadata_fields:
    - filename
    - page_number
    - document_type
    - author
    - date_modified
    - source_path
    - ocr_confidence
    - summary
    
  # Types de documents supportés
  supported_formats:
    - pdf
    - docx
    - txt
    - msg
    - eml
    - jpg
    - png
    
  # Paramètres OCR (Google Vision)
  ocr:
    enable: true
    language_hints: ["fr"]
    confidence_threshold: 0.7
    max_pages_per_request: 10
    monthly_quota: 100000
    
  # Stratégies de chunking par type
  chunking_strategies:
    legal_document:
      chunk_size: 1000
      chunk_overlap: 150
      preserve_paragraphs: true
      
    correspondence:
      chunk_size: 500
      chunk_overlap: 50
      preserve_sentences: true
      
    financial_document:
      chunk_size: 600
      chunk_overlap: 100
      preserve_tables: true

# Configuration de la recherche
search:
  # Nombre de résultats par défaut
  default_k: 10
  
  # Score minimum de pertinence
  min_relevance_score: 0.5
  
  # Reranking
  enable_reranking: true
  rerank_top_k: 20
  
  # Filtres par défaut
  default_filters:
    exclude_drafts: true
    exclude_archived: true
    
  # Boost de pertinence par type
  relevance_boost:
    jurisprudence: 1.5
    code_article: 1.3
    plaidoirie: 1.2
    correspondance: 1.0
    
# Configuration de la base de données
database:
  # Type de collection ChromaDB
  collection_name: "legal_vectors"
  
  # Distance metric
  distance_metric: "cosine"
  
  # Indexation
  index_type: "hnsw"
  hnsw_space: "cosine"
  hnsw_construction_ef: 200
  hnsw_search_ef: 100
  
# Paramètres de performance
performance:
  # Cache
  enable_cache: true
  cache_ttl: 3600  # 1 heure
  cache_size_mb: 500
  
  # Parallélisation
  max_workers: 4
  async_processing: true
  
  # Limites
  max_document_size_mb: 50
  max_batch_size_mb: 100
  
# Paramètres de sécurité
security:
  # Chiffrement des vecteurs sensibles
  encrypt_vectors: false  # Activer si nécessaire
  
  # Anonymisation
  anonymize_personal_data: true
  personal_data_patterns:
    - email
    - phone
    - social_security
    - bank_account
    
  # Audit
  log_all_queries: true
  log_vector_operations: false
